### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [gmazzamuto/MAX1464-Arduino-library#1]
Hi @gmazzamuto   

we have detected a discrepancy in the library name written inside `library.properties`
  `MAX1464 Arduino library`
and the library name written inside inside the library manager index:
  `MAX1464`

I think this is due to an error on our side when the library was registered in the library manager index (at the times this process was mostly manual).

Now we are about to introduce a change in the library manager that forbids the situation described above and the releases whose name differs from the name registered in the library index are ignored.

Is it ok for you to use the name `MAX1464 Arduino library`? If yes, the library will be re-published with the name `MAX1464 Arduino library` and the old `MAX1464` will be removed from the index, in this case no action is needed on your side. In absence of an answer from you we will proceed with this proposal next week.

Thanks

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 621 - 2018/01/15 15:43:21 Scraping https://github.com/gmazzamuto/MAX1464-Arduino-library.git
JOB 621 - 2018/01/15 15:43:22 Checking out tag: v1.0.0
JOB 621 - 2018/01/15 15:43:22 Release MAX1464 Arduino library:1.0.0 has wrong library name, should be MAX1464
```

**Comment by gmazzamuto** [comment]
That's fine for me!

Thank you very much
